### ISSUE TITLE
diagrama E/R

### ISSUE THREAD

**Issue by raulordas** [StevenRosero/ProIntegradortrecerTrimestre#1]
Documento pdf con el esquema entidad relacion

**Comment by raulordas** [comment]
[Diagrama_Entidad_Relacion_IntegraApp.pdf](https://github.com/StevenRosero/ProIntegradortrecerTrimestre/files/1890918/Diagrama_Entidad_Relacion_IntegraApp.pdf)

**Comment by raulordas** [comment]
Pendiente de revisar y normalizar

**Comment by StevenRosero** [comment]
Que grande me gusta el formato y la idea se nota que se te da genial! mañana lo vemos a fondo
