### ISSUE TITLE
-[BD3]Generación del Modelo Relacional y normalización

### ISSUE THREAD

**Issue by jinchengweng** [StevenRosero/ProIntegradortrecerTrimestre#18]

**Comment by jinchengweng** [comment]
el modelo ya está
completo, solo falta consultar la normalización del mismo

**Comment by StevenRosero** [comment]
[3 NORMALIZACIÓN.docx](https://github.com/StevenRosero/ProIntegradortrecerTrimestre/files/1915206/3.NORMALIZACION.docx)
queda informacion por rellenar

**Comment by StevenRosero** [comment]
Vale equipo subo el PDF final del apartado de Normalización  la base de datos para que el cloudMaster lo suba @jinchengweng 
[INTEGRAAPP DOCUMENTO Bases de datos 1.pdf](https://github.com/StevenRosero/ProIntegradortrecerTrimestre/files/1931913/INTEGRAAPP.DOCUMENTO.Bases.de.datos.1.pdf)
