### ISSUE TITLE
[ED5] GENERACIÓN DE DIAGRAMA DE CLASES

### ISSUE THREAD

**Issue by jinchengweng** [StevenRosero/ProIntegradortrecerTrimestre#23]

**Comment by StevenRosero** [comment]
<img width="542" alt="cap3vistatotal" src="https://user-images.githubusercontent.com/36227488/40606422-9be1344c-6265-11e8-8c51-92f23fb6f457.PNG">
<img width="636" alt="cap1" src="https://user-images.githubusercontent.com/36227488/40606423-9bfe037e-6265-11e8-952a-30bca6c2992f.PNG">
<img width="731" alt="cap2" src="https://user-images.githubusercontent.com/36227488/40606425-9c24e39a-6265-11e8-9e5e-9831397a5bcf.PNG">
<img width="747" alt="cap31" src="https://user-images.githubusercontent.com/36227488/40606426-9c444b36-6265-11e8-9180-7c80d62e4d99.PNG">
<img width="558" alt="cap32" src="https://user-images.githubusercontent.com/36227488/40606428-9c619920-6265-11e8-83e6-e7d3fd1c7ad9.PNG">
