### ISSUE TITLE
Análisis de las especificaciones del proyecto

### ISSUE THREAD

**Issue by StevenRosero** [StevenRosero/ProIntegradortrecerTrimestre#4]
Entornos

**Comment by raulordas** [comment]
[IntegraApp1.0.pdf](https://github.com/StevenRosero/ProIntegradortrecerTrimestre/files/1895659/IntegraApp1.0.pdf)
[Carpeta INTEGRAAPP DOCUMENTO PROYECTO.zip](https://github.com/StevenRosero/ProIntegradortrecerTrimestre/files/1895661/Carpeta.INTEGRAAPP.DOCUMENTO.PROYECTO.zip)

**Comment by raulordas** [comment]
Re-subo el pdf porque no se si subió correctamente en el commit anterior.

[IntegraApp1.0_100418.pdf](https://github.com/StevenRosero/ProIntegradortrecerTrimestre/files/1895736/IntegraApp1.0_100418.pdf)
